version: '3'

services:

  db:
    image: "postgres:16.2"
    command: ["postgres", "-c", "max_connections=300"]
    environment:
      POSTGRES_MULTIPLE_DATABASES: keycloakdb,hrdb,trackerdb,accounterdb,dashikdb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "25432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:rw
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d


  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpass
      RABBITMQ_DEFAULT_VHOST: rabbit
    volumes:
      - ./services/broker/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./services/broker/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "15672:15672"


  keycloak:
    image: "quay.io/keycloak/keycloak:latest"
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_pass
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloakdb
      KC_DB_USERNAME: dbuser
      KC_DB_PASSWORD: dbpassword
      KC_HOSTNAME_STRICT: false
      KC_FEATURES: token-exchange
    ports:
      - "8080:8080"


  hr-api:
    build: services/hr
    command: python3 manage.py runserver 0.0.0.0:8000
#    ports:
#      - "8001:8000"


  tracker-worker:
    build: services/tracker
    command: python3 manage.py worker
    depends_on:
      - rabbitmq


  tracker-api:
    build: services/tracker
    command: python3 manage.py runserver 0.0.0.0:8000


  accounter-worker:
    build: services/accounter
    command: python3 manage.py worker
    depends_on:
      - rabbitmq


  accounter-api:
    build: services/accounter
    command: python3 manage.py runserver 0.0.0.0:8000


  oauth-proxy:
    image: "quay.io/oauth2-proxy/oauth2-proxy:v7.6.0-alpine"
    # KeyCloak config as per https://oauth2-proxy.github.io/oauth2-proxy/configuration/providers/keycloak_oidc
    command:
      - --client-id=gupop
      - --client-secret=qEt6LkZBoz9CGEh89lbWuysZik6d6aV4
      - --cookie-secret=emYQA-u4UJP38oNst9r-rXqkMVYAoYsj8mH6HbgjRqc=
      - --email-domain=*
      - --http-address=0.0.0.0:80
      - --upstream=http://hr-api:8000/api/hr/
      - --upstream=http://tracker-api:8000/api/tracker/
      - --upstream=http://accounter-api:8000/api/accounting/
      - --provider=keycloak-oidc
      - --redirect-url=http://127.0.0.1:8000/oauth2/callback
      - --oidc-issuer-url=http://keycloak:8080/realms/master
      - --insecure-oidc-skip-issuer-verification
      - --insecure-oidc-allow-unverified-email
      - --code-challenge-method=S256
    ports:
      - "8000:80"
    depends_on:
      - keycloak


volumes:
  db_data: {}
